---
name: Jasdeep 
surname: Singh
# profilepic: jasdeep-552x600.jpg
position: "Senior Cloud Engineer (Security and Performance)"
address: "PG5A, Sector 108, Mohali, Punjab, India"
phone: +91 9988638850
www: jasdeep-singh.com
email: "jasdeep.jogewala@gmail.com"
twitter: jasdeep
github: jasdeep
linkedin: jasdeep
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 03045E
# aboutme: "With more than 15 years of experience in designing, developing and delivering enterprise software, I take initiative and lead the engineering projects that bring robustness and resiliency to the services offered. My recent work involves security and performance engineering. I have worked on security vulnerability mitigation, migration to cloud infrastructre, performance bug resolution, and introducing concurrency."
output: 
  vitae::awesomecv:
    page_total: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(magrittr)
source("utils/data_download_funs.R")
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1e8KYdJ5P_mAE9UyaOi_2U4Sj12g2ZCkguzhFKYY0L50/edit?usp=sharin",  
  pdf_mode = FALSE
)
```


# Career Summary

\cvparagraph
```{r results='asis'}
CV %<>% print_text_block("intro")
```



# Experience 

```{r}
CV$entries_data %>% 
  filter(section == 'industry_positions') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```


<!-- ``` -->


# Projects 

```{r}
CV$entries_data %>% 
  filter(section == 'personal_projects') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```





# Skills
```{r, results='asis'}
CV %>% print_skill()
```





# Writings
```{r}
CV$entries_data %>% 
  filter(section == 'academic_articles') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```


# Certification


```{r}
CV$entries_data %>% 
  filter(section == 'certification') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```



# Education
```{r}
CV$entries_data %>% 
  filter(section == 'education') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```



<!-- ```{r} -->
<!-- CV$entries_data %>%  -->
<!--   filter(section == 'skills') %>%  -->
<!--   detailed_entries( -->
<!--     with = title, -->
<!--     what = description_bullets -->
<!--   ) -->
<!-- ``` -->

